general:
  # device: [cuda:0, cuda:1, cuda:2, cuda:3]
  device: cuda
  output: newtonnet_train
  precision: double
  seed: 0

data:
  train_root: Data/rMD17/splits/rmd17_aspirin/split_01/train
  # val_root: Data/rMD17/splits/rmd17_aspirin/split_01/test
  test_root: Data/rMD17/splits/rmd17_aspirin/split_01/test
  train_size: 950
  val_size: null
  test_size: null
  train_batch_size: 10
  val_batch_size: 1000
  test_batch_size: 1000
  cutoff: 5.0
  force_reload: True

model:
  pretrained_model: null
  representation:
    cutoff_network: poly
    radial_network: bessel
    n_basis: 20
  n_features: 128
  n_interactions: 3
  activation: swish
  train_scaler: True
  # infer_properties: ['energy', 'gradient_force', 'direct_force']
  infer_properties: ['energy', 'gradient_force']

training:
  # wandb:
  #   project: NewtonNet
  #   name: null
  loss: 
    energy:
      weight: 1.0
      mode: mse
    gradient_force:
      weight: 50.0
      mode: mse
    # direct_force:
    #   weight: 0.0
    #   mode: mse
    #   transform: cos
  optimizer: 
    adam:
      lr: 1.0e-3
      weight_decay: 0.0
      amsgrad: False
  lr_scheduler: 
    plateau:
      patience: 15
      factor: 0.7
      min_lr: 1.0e-5
  epochs: 10001
  clip_grad: 0.0
  checkpoint:
    check_val: 1
    check_test: 10
    check_log: 10

